---
- name: Converge
  hosts: all
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "example.com www.example.com"
        return: "301 https://$host$request_uri"
        filename: example.com.80.conf
      - listen: "443 ssl http2"
        server_name: "example.com www.example.com"
        server_redirect_name: www.example.com
        filename: example.com.443.conf
        extra_parameters: |
          # SSL config
          ssl_session_cache         builtin:1000  shared:SSL:10m;
          ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
          ssl_ciphers               HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
          ssl_prefer_server_ciphers on;
          ssl_certificate           /etc/ssl/certs/test.pem;
          ssl_certificate_key       /etc/ssl/private/test.key;

          # Reverse proxy
          location / {
              proxy_set_header    Host $host;
              proxy_set_header    X-Real-IP $remote_addr;
              proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header    X-Forwarded-Proto $scheme;

              proxy_pass          https://google.com/;
              proxy_read_timeout  90;
              proxy_redirect      http://localhost https://google.com;
          }

  roles:
    - role: nginx
